// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	Message
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Types
type Message struct {
	Sender     string `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Text       string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Register   bool   `protobuf:"varint,3,opt,name=register" json:"register,omitempty"`
	Disconnect bool   `protobuf:"varint,4,opt,name=disconnect" json:"disconnect,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto1.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto1.RegisterType((*Message)(nil), "proto.Message")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Chat service

type ChatClient interface {
	TransferMessage(ctx context.Context, opts ...grpc.CallOption) (Chat_TransferMessageClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) TransferMessage(ctx context.Context, opts ...grpc.CallOption) (Chat_TransferMessageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Chat_serviceDesc.Streams[0], c.cc, "/proto.Chat/TransferMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatTransferMessageClient{stream}
	return x, nil
}

type Chat_TransferMessageClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatTransferMessageClient struct {
	grpc.ClientStream
}

func (x *chatTransferMessageClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatTransferMessageClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Chat service

type ChatServer interface {
	TransferMessage(Chat_TransferMessageServer) error
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_TransferMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).TransferMessage(&chatTransferMessageServer{stream})
}

type Chat_TransferMessageServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type chatTransferMessageServer struct {
	grpc.ServerStream
}

func (x *chatTransferMessageServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatTransferMessageServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferMessage",
			Handler:       _Chat_TransferMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x85, 0x5c, 0xec, 0xbe, 0xa9,
	0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0xa9, 0x79, 0x29, 0xa9, 0x45, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x90, 0x10, 0x17, 0x4b, 0x49, 0x6a, 0x45, 0x89,
	0x04, 0x13, 0x58, 0x14, 0xcc, 0x16, 0x92, 0xe2, 0xe2, 0x28, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49,
	0x2d, 0x92, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x08, 0x82, 0xf3, 0x85, 0xe4, 0xb8, 0xb8, 0x52, 0x32,
	0x8b, 0x93, 0xf3, 0xf3, 0xf2, 0x52, 0x93, 0x4b, 0x24, 0x58, 0xc0, 0xb2, 0x48, 0x22, 0x46, 0xf6,
	0x5c, 0x2c, 0xce, 0x19, 0x89, 0x25, 0x42, 0xe6, 0x5c, 0xfc, 0x21, 0x45, 0x89, 0x79, 0xc5, 0x69,
	0xa9, 0x45, 0x30, 0x27, 0xf0, 0x41, 0x1c, 0xa7, 0x07, 0xe5, 0x4b, 0xa1, 0xf1, 0x95, 0x18, 0x34,
	0x18, 0x0d, 0x18, 0x93, 0xd8, 0xc0, 0x82, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xf7,
	0xdc, 0xa1, 0xcf, 0x00, 0x00, 0x00,
}
